version: "3"

services:
  pulsar:
    image: apachepulsar/pulsar:3.2.2
    command: bin/pulsar standalone
    hostname: pulsar
    container_name: pulsar
    ports:
      - "8080:8080"
      - "6650:6650"
    restart: always
    volumes:
      - "./data:/pulsar/data"
  dashboard:
    image: apachepulsar/pulsar-manager:v0.4.0
    ports:
      - "9527:9527"
      - "7750:7750"
    container_name: dashboard
    depends_on:
      - pulsar
    links:
      - pulsar
    environment:
      SPRING_CONFIGURATION_FILE: /pulsar-manager/pulsar-manager/application.properties